### ISSUE TITLE
Decide how to compare the two data-sets

### ISSUE THREAD

**Issue by Logan-Selley** [tleung22/final-project#2]

**Comment by Aguirj1995** [comment]
So we decided that one of the visualizations would be an interactive map that would display all states along with where they fall on the scale of the happiness index. I think the best way to represent this would be by color-coding each state based on the scale. Furthermore, we will add hover text on each state so that when the user hovers over it, they will be able to gun sales per state. 

For the second visualization, we agree to do a bar chart. The chart will focus specifically on the shootings recorded in each state along with - deaths, injured, whether or not the state has legislation or is proposing legislation on guns, and any other variables we think fit in with all of these. The bar chart should be the visualization that really drives home the issue of gun violence in the United States.

Not sure if I might have missed anything from what we talked about yesterday? Feel free to edit this.
